### PR TITLE
Fix threshold option typo.

### PR DESCRIPTION
**Pull request by Hyperkid123**
Can you make sure it did not break anything? I did went through the demo and it seems to work fine but sill.

### CODE REVIEW

**Comment by rvsia** [comment]
@Hyperkid123 the typo in in formschemas page too. If you are running MiQ, in flavor form there are many threshold values, you can test it (or fix that typo). I am not sure if I will get to test it this week.

**Comment by rvsia** [comment]
@Hyperkid123 actually this leads me to a question: why we have thresholds and values?

**Comment by Hyperkid123** [comment]
@rvsia the name is just deprecated you can still use both but we won't show that.

I don't get the second question.

**Comment by rvsia** [comment]
@Hyperkid123 what is the difference between “value” and “threshold” keys in validators? I think we could unify these keys and use only one.

**Comment by Hyperkid123** [comment]
Yes i was thinking about it too. threshold is used in length validators and value is used when actually comparing value to something

**Comment by rvsia** [comment]
I would unify it and have it consistent. I dont think we need make differences accross validators keys, because validators make the differences. What do you think?

**Comment by Hyperkid123** [comment]
we can but we still need to leave these in for some time and mark them as deprecated

**Comment by rvsia** [comment]
@Hyperkid123 package.json and lock are included

**Comment by Hyperkid123** [comment]
oghhh crap what did i doo
:smile:

**Pull request merged**
